xbee/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.apps import apps


urlpatterns = i18n_patterns(
    path('administration/', admin.site.urls),
    path('', include('xbee_account.urls')),

)

for app in settings.INSTALLED_APPS:
    if app.startswith('xbee_'):
        app_config = apps.get_app_config(app.rsplit('.')[0])
        if hasattr(app_config, 'urls') and app_config.urls:
            urlpatterns += i18n_patterns(
                path(f'{app_config.urls}/', include(f'{app_config.name}.urls')),
            )

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    import debug_toolbar
    urlpatterns = [
        path('debug/', include(debug_toolbar.urls)),
    ] + urlpatterns

xbee_account/urls.py
from django.urls import path

from xbee_account import views

app_name = 'xbee_account'

urlpatterns = [
    path('', views.DashboardView.as_view(), name='dashboard'),
    path('users-list/', views.users_list, name='users_list'),
    path('user/detail/<int:user_id>', views.user_detail, name='account'),
    path('user/disable/<int:user_id>', views.user_disable, name='user_disable'),

    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),

]

xbee_extensions/urls.py
from django.urls import path

from xbee_extensions import views

app_name = 'xbee_extensions'

urlpatterns = [
    path('', views.ExtensionsView.as_view(), name='extensions_list'),
    path('create/', views.ExtensionCreateView.as_view(), name='extension_create'),
    path('detail/<int:id_ext>', views.ExtensionDetailView.as_view(), name='extension_detail'),
    path('followme/delete/<int:id_followme>', views.DeleteFollowMeView.as_view(), name='delete_follow_me'),
    path('followme/disable/<int:id_followme>', views.DisableFollowMeView.as_view(), name='disable_follow_me'),

]

xbee_extensions/forms.py
from django import forms
from django.forms import ModelForm
from django.urls import reverse_lazy

from xbee_extensions.models import Extension, FollowMe, SipFriends
from xbee_modules.models import Module


class ExtensionForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if initial := kwargs.get('initial'):
            self.fields['secret'].queryset = initial.get('secret', '')
            if comps := initial.get('companies', False):
                self.fields['company'].queryset = comps

    class Meta:
        model = Extension
        fields = '__all__'
        exclude = ('parameters', 'name', 'context', 'caller_id', 'ring_time')


class ExtensionEditForm(ModelForm):
    host = forms.CharField(required=False)
    type = forms.ChoiceField(required=False, choices=SipFriends.TYPE_CHOICES)
    nat = forms.ChoiceField(required=False, choices=SipFriends.NAT_CHOICES)
    busylevel = forms.IntegerField(required=False)
    qualify = forms.CharField(required=False)
    permit = forms.CharField(required=False)
    deny = forms.CharField(required=False)
    transport = forms.ChoiceField(required=False, choices=SipFriends.TRASPORT_CHOICES)
    dtmfmode = forms.ChoiceField(required=False, choices=SipFriends.DTMFMODE_CHOICES)
    directmedia = forms.ChoiceField(required=False, choices=SipFriends.DIRECTMEDIA_CHOICES)
    defaultuser = forms.CharField(required=False)
    callgroup = forms.CharField(required=False)
    pickupgroup = forms.CharField(required=False)
    language = forms.CharField(required=False)
    allow = forms.CharField(required=False)
    disallow = forms.CharField(required=False)
    insecure = forms.CharField(required=False)
    trustrpid = forms.ChoiceField(required=False, choices=SipFriends.YES_NO_CHOICES)
    progressinband = forms.ChoiceField(required=False, choices=SipFriends.PROGRESSINBAND_CHOICES)
    accountcode = forms.CharField(required=False)
    callerid = forms.CharField(required=False)
    callcounter = forms.ChoiceField(required=False, choices=SipFriends.YES_NO_CHOICES)
    videosupport = forms.ChoiceField(required=False, choices=SipFriends.YES_NO_CHOICES)
    mailbox = forms.CharField(required=False)
    session_timers = forms.ChoiceField(required=False, choices=SipFriends.SESSION_TIMERS_CHOICES)
    session_expires = forms.IntegerField(required=False)
    session_minse = forms.IntegerField(required=False)
    session_refresher = forms.ChoiceField(required=False, choices=SipFriends.SESSION_REFRESHER_CHOICES)
    t38pt_usertpsource = forms.CharField(required=False)
    qualifyfreq = forms.IntegerField(required=False)
    faxdetect = forms.ChoiceField(required=False, choices=SipFriends.YES_NO_CHOICES)
    fullname = forms.CharField(required=False)
    cid_number = forms.CharField(required=False)
    call_limit = forms.IntegerField(required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if initial := kwargs.get('initial'):
            if comps := initial.get('companies', False):
                self.fields['company'].queryset = comps

    def load(self):
        """
            Call this method after initialization in the view
        """
        for key, value in self.instance.parameters.items():
            self.fields[key].initial = value

    def dump(self):
        """
            Call this method after is_valid() and before save()
        """
        new_parameters = {}
        for key, value in self.instance.parameters.items():
            new_parameters[key] = self.cleaned_data[key]
        self.instance.parameters = new_parameters

    class Meta:
        model = Extension
        fields = '__all__'
        exclude = ('parameters',)


class FollowMeForm(ModelForm):

    module_destination_busy = forms.ModelChoiceField(
        queryset=Module.objects.all(),
        required=False,
        widget=forms.Select(
            attrs={
                'my-id': 'module_select_ajax', 'url': reverse_lazy('xbee_modules:modules_ajax_list'),
            }
        )
    )
    sub_module_destination_busy = forms.CharField(required=False, widget=forms.Select(attrs={
        'my-id': 'module_select_ajax_sub',
    }))

    module_destination_no_answer = forms.ModelChoiceField(
        queryset=Module.objects.all(),
        required=False,
        widget=forms.Select(
            attrs={
                'my-id': 'module_select_ajax', 'url': reverse_lazy('xbee_modules:modules_ajax_list'),
            }
        )
    )
    sub_module_destination_no_answer = forms.CharField(required=False, widget=forms.Select(attrs={
        'my-id': 'module_select_ajax_sub',
    }))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if initial := kwargs.get('initial'):
            if mohc := initial.get('music_on_holding', False):
                self.fields['music_on_holding'].queryset = mohc
        self.fields['enable'].widget.attrs['min'] = 0
        self.fields['enable'].widget.attrs['max'] = 1

        self.fields['module_destination_busy'].new_group = 'true'
        self.fields['module_destination_no_answer'].new_group = 'true'

    def save(self, commit=True):
        followme_obj = super().save(commit=False)
        if self.cleaned_data['module_destination_busy'] and self.cleaned_data['sub_module_destination_busy']:
            model_class_module = self.cleaned_data['module_destination_busy'].model_object.model_class()
            followme_obj.destination_busy = model_class_module.objects.get(
                pk=self.cleaned_data['sub_module_destination_busy']
            )

        if self.cleaned_data['module_destination_no_answer'] and self.cleaned_data['sub_module_destination_no_answer']:
            model_class_module = self.cleaned_data['module_destination_no_answer'].model_object.model_class()
            followme_obj.destination_no_answer = model_class_module.objects.get(
                pk=self.cleaned_data['sub_module_destination_no_answer']
            )

        if commit:
            followme_obj.save()

        return followme_obj

    class Meta:
        model = FollowMe
        fields = '__all__'
        exclude = ('extension', 'type', 'destination_busy_content_type', 'destination_busy_object_id',
                   'destination_busy', 'destination_no_answer_content_type', 'destination_no_answer_object_id',
                   'destination_no_answer')

xbee_extensions/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms import formset_factory
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.template.loader import render_to_string
from django.utils.crypto import get_random_string
from django.utils.translation import ugettext_lazy as _

from utils.base_class_view import BaseClassView
from xbee_company.models import Company
from xbee_extensions.forms import ExtensionForm, ExtensionEditForm, FollowMeForm
from xbee_extensions.models import Extension, FollowMe


class ExtensionsView(LoginRequiredMixin, BaseClassView):
    """
        List all extensions
    """

    template_name = 'xbee_extensions/extensions_list.html'

    def get(self, request):
        comps = self.get_companies_by_user(request)
        exts = Extension.objects.filter(company__in=comps)
        return render(request, self.template_name, {'extensions': exts})


class ExtensionCreateView(LoginRequiredMixin, BaseClassView):
    """
        Create new estensions
    """

    template_name = 'xbee_extensions/extension_create.html'
    redirect_url = 'xbee_extensions:extensions_list'

    def post(self, request):
        if request.is_ajax():
            first_ext = int(request.POST.get('first_ext'))
            last_ext = int(request.POST.get('last_ext'))
            num_extra = last_ext - first_ext + 1

            ExtensionFormset = formset_factory(ExtensionForm, extra=num_extra)
            comps = self.get_companies_by_user(request)
            ext_formset = ExtensionFormset(form_kwargs={
                'initial': {
                    'companies': comps,
                    'secret': get_random_string(length=20)
                }
            })
            for idx, frm in enumerate(ext_formset):
                frm.fields['number'].initial = first_ext + idx

            context = {'ext_formset': ext_formset}
            html_template = render_to_string("xbee_extensions/extension_formset.html", context, request=request)
            return HttpResponse(html_template)

        ExtensionFormset = formset_factory(ExtensionForm)
        ext_formset = ExtensionFormset(request.POST)
        if ext_formset.is_valid():
            for frm in ext_formset:
                if frm.is_valid():
                    extens = frm.save(commit=False)
                    comp_id = str(extens.company.pk).zfill(11)  # TODO ricontrolla quando attivi vision

                    extens.name = f'{comp_id}-{extens.number}'
                    extens.context = f'{comp_id}-cos-general'
                    extens.caller_id = extens.number
                    extens.parameters = {
                        'host': 'dynamic',
                        'type': 'friend',
                        'nat': 'yes',
                        'busylevel': 1,
                        'qualify': 'no',
                        'permit': '', 'deny': '', 'transport': '', 'dtmfmode': '', 'directmedia': '',
                        'defaultuser': '', 'callgroup': '', 'pickupgroup': '', 'language': '', 'allow': '',
                        'disallow': '', 'insecure': '', 'trustrpid': '', 'progressinband': '', 'accountcode': '',
                        'callerid': '', 'callcounter': '', 'videosupport': '', 'mailbox': '', 'session_timers': '',
                        'session_expires': 3600, 'session_minse': None, 'session_refresher': '',
                        't38pt_usertpsource': '', 'qualifyfreq': None, 'faxdetect': '', 'fullname': '',
                        'cid_number': '', 'call_limit': None
                    }
                    extens.save()

        return redirect(self.redirect_url)

    def get(self, request):
        return render(request, self.template_name)


class ExtensionDetailView(LoginRequiredMixin, BaseClassView):

    template_name = 'xbee_extensions/extension_detail.html'

    def post(self, request, id_ext):
        ext = get_object_or_404(Extension, pk=id_ext)

        if 'ext_detail_submitted' in request.POST:
            form = ExtensionEditForm(request.POST, instance=ext)
            if form.is_valid():
                form.dump()
                form.save()
                messages.success(request, _("Extension updated!"))
        else:
            form = FollowMeForm(request.POST)
            if form.is_valid():
                fwme = form.save(commit=False)
                fwme.extension = ext
                if 'followme_0_submitted' in request.POST:
                    fwme.type = 0
                else:
                    fwme.type = 1

                fwme.save()
                messages.success(request, _("Followme added!"))

        return redirect(ext)

    def get(self, request, id_ext):
        ext = get_object_or_404(Extension, pk=id_ext)
        comps = Company.objects.filter(pk=ext.company.pk)
        form_ext = ExtensionEditForm(instance=ext, initial={'companies': comps})
        form_ext.load()

        followme_internal = FollowMe.objects.filter(extension=ext, type=0)
        followme_external = FollowMe.objects.filter(extension=ext, type=1)
        form_followme = FollowMeForm(initial={'music_on_holding': comps.first().company_music_categories.all()})

        return render(request, self.template_name, {
            'ext': ext,
            'form_ext': form_ext,
            'followme_internal': followme_internal,
            'followme_external': followme_external,
            'form_followme': form_followme,
        })


class DeleteFollowMeView(LoginRequiredMixin, BaseClassView):
    def get(self, request, id_followme):
        fwme = get_object_or_404(FollowMe, pk=id_followme)
        ext = fwme.extension
        fwme.delete()
        messages.success(request, _("Followme deleted!"))

        return redirect(ext)


class DisableFollowMeView(LoginRequiredMixin, BaseClassView):
    def get(self, request, id_followme):
        fwme = get_object_or_404(FollowMe, pk=id_followme)
        if fwme.enable == 1:
            fwme.enable = 0
            messages.success(request, _("Followme disabled!"))
        else:
            fwme.enable = 1
            messages.success(request, _("Followme enabled!"))
        fwme.save()

        return redirect(fwme.extension)

xbee_extensions/templates/xbee_extensions/extension_create.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block title %}{% trans "Create Extension" %}{% endblock %}

{% block css_head_block %}
    <link rel="stylesheet" href="{% static "css/vendor/bootstrap-float-label.min.css" %}" />
    <link rel="stylesheet" href="{% static "css/vendor/dataTables.bootstrap4.min.css" %}" />
    <link rel="stylesheet" href="{% static "css/vendor/datatables.responsive.bootstrap4.min.css" %}" />

    <link rel="stylesheet" href="{% static "css/vendor/smart_wizard.min.css" %}" />
{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-12">
            <h1>{% trans "Create extension" %}</h1>
            <nav class="breadcrumb-container d-none d-sm-block d-lg-inline-block" aria-label="breadcrumb">
                <ol class="breadcrumb pt-0">
                    <li class="breadcrumb-item"><a href="{% url "xbee_account:dashboard" %}">{% trans "Home" %}</a></li>
                    <li class="breadcrumb-item"><a href="{% url "xbee_extensions:extensions_list" %}">{% trans "Extension list" %}</a></li>
                    <li class="breadcrumb-item active" aria-current="page">{% trans "Create extension" %}</li>
                </ol>
            </nav>
            <div class="separator mb-5"></div>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <div class="card mb-4">
                <div id="smartWizardValidation">
                    <ul class="card-header">
                        <li><a href="#step-0">Step 1<br /><small>{% trans "Extensions number" %}</small></a></li>
                        <li><a href="#step-1">Step 2<br /><small>{% trans "Extensions details" %}</small></a></li>
                    </ul>

                    <div class="card-body">
                        <div id="step-0">
                            <form id="form-step-0" class="tooltip-label-right" novalidate>
                                <div class="form-group position-relative error-l-100">
                                    <label for="first-ext">{% trans "First extension identifier" %}</label>
                                    <input type="number" id="first-ext" class="form-control" required>
                                </div>
                                <div class="form-group position-relative error-l-100">
                                    <label for="last-ext">{% trans "Last extension identifier" %}</label>
                                    <input type="number" id="last-ext" class="form-control" required>
                                </div>
                            </form>
                        </div>
                        <div id="step-1" style="min-height: 180px; height: auto;">
                            <div id="spinner" class="text-center">
                                <div class="my-spinner"></div>
                            </div>
                            <div id="result-formset"></div>
                        </div>
                    </div>

                    <div class="btn-toolbar custom-toolbar text-center card-body pt-0">
                        <button class="btn btn-secondary prev-btn" type="button">{% trans "Previous" %}</button>
                        <button class="btn btn-secondary next-btn" type="button" onclick="formsetAjax();">{% trans "Next" %}</button>
                    </div>
                </div>
            </div>
        </div>

    </div>

{% endblock %}

{% block js_body_block %}
    <script src="{% static "js/vendor/datatables.min.js" %}"></script>

    <script src="{% static "js/vendor/jquery.smartWizard.min.js" %}"></script>
    <script src="{% static "js/vendor/jquery.validate/jquery.validate.min.js" %}"></script>

    <script>
        function formsetAjax() {
            $.post(window.location.href, {first_ext: $('#first-ext').val(), last_ext: $('#last-ext').val()})
                .done(function(data) {
                    $('#spinner').hide();
                    $('#result-formset').html(data);
                    $('.add-form-row').hide();
                });
        }
    </script>
{% endblock %}

xbee_extensions/templates/xbee_extensions/extension_detail.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block title %}{{ ext.name }} ~ {% trans "Extension detail" %}{% endblock %}

{% block css_head_block %}
    <link rel="stylesheet" href="{% static "css/vendor/bootstrap-float-label.min.css" %}" />
    <link rel="stylesheet" href="{% static "css/vendor/dataTables.bootstrap4.min.css" %}" />
    <link rel="stylesheet" href="{% static "css/vendor/datatables.responsive.bootstrap4.min.css" %}" />
{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-12">
            <h1>{% trans "Extension detail" %}</h1>
            <nav class="breadcrumb-container d-none d-sm-block d-lg-inline-block" aria-label="breadcrumb">
                <ol class="breadcrumb pt-0">
                    <li class="breadcrumb-item"><a href="{% url "xbee_account:dashboard" %}">{% trans "Home" %}</a></li>
                    <li class="breadcrumb-item"><a href="{% url "xbee_extensions:extensions_list" %}">{% trans "Extensions list" %}</a></li>
                    <li class="breadcrumb-item active" aria-current="page">{{ ext.name }} ~ {% trans "Extension detail" %}</li>
                </ol>
            </nav>
            <div class="separator mb-5"></div>
        </div>
    </div>

    <div class="row mb-4">
        <div class="col-12">
            <div class="card">
                <div class="card-body">

                    {% with submit_text="Edit" submit_name="ext_detail_submitted" form=form_ext %}{% include "form-grid.html" %}{% endwith %}

                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <h2>{% trans "Follow Me" %}</h2>
        </div>
    </div>

    <div class="row mb-4">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <ul class="nav nav-tabs card-header-tabs " role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" id="first-tab" data-toggle="tab" href="#followme__internal" role="tab" aria-controls="first" aria-selected="true">{% trans "Internal" %}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="second-tab" data-toggle="tab" href="#followme__external" role="tab" aria-controls="second" aria-selected="false">{% trans "External" %}</a>
                        </li>
                    </ul>
                </div>

                <div class="card-body">

                    <div class="tab-content">
                        <div class="tab-pane fade show active" id="followme__internal" role="tabpanel" aria-labelledby="first-tab">

                            {% with followme=followme_internal type=0 %}{% include "xbee_extensions/tab/follow_me_section.html" %}{% endwith %}

                        </div>
                        <div class="tab-pane fade" id="followme__external" role="tabpanel" aria-labelledby="second-tab">

                            {% with followme=followme_external type=1 %}{% include "xbee_extensions/tab/follow_me_section.html" %}{% endwith %}

                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block js_body_block %}
    <script src="{% static "js/vendor/datatables.min.js" %}"></script>
{% endblock %}

xbee_extensions/templates/xbee_extensions/extension_formset.html
{% with submit_text="Create" submit_name="fs_ext_submitted" formset=ext_formset %}{% include "formset-grid.html" %}{% endwith %}

xbee_extensions/templates/xbee_extensions/extensions_list.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block title %}{% trans "Extension list" %}{% endblock %}

{% block css_head_block %}
    <link rel="stylesheet" href="{% static "css/vendor/bootstrap-float-label.min.css" %}" />
    <link rel="stylesheet" href="{% static "css/vendor/dataTables.bootstrap4.min.css" %}" />
    <link rel="stylesheet" href="{% static "css/vendor/datatables.responsive.bootstrap4.min.css" %}" />
{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-12">
            <h1>{% trans "Extension list" %}</h1>
            <div class="top-right-button-container">
                <a href="{% url "xbee_extensions:extension_create" %}"><button type="button" class="btn btn-primary btn-lg top-right-button mr-1">{% trans "ADD" %}</button></a>
            </div>
            <nav class="breadcrumb-container d-none d-sm-block d-lg-inline-block" aria-label="breadcrumb">
                <ol class="breadcrumb pt-0">
                    <li class="breadcrumb-item"><a href="{% url "xbee_account:dashboard" %}">{% trans "Home" %}</a></li>
                    <li class="breadcrumb-item active" aria-current="page">{% trans "Extension list" %}</li>
                </ol>
            </nav>
            <div class="separator mb-5"></div>
        </div>
    </div>

    <div class="row mb-4">
        <div class="col-12">
            <div class="card">
                <div class="card-body">

                    <table class="data-table data-tables-pagination responsive nowrap" data-order="[[ 1, &quot;desc&quot; ]]">
                        <thead>
                            <tr>
                                <th>{% trans "Name" %}</th>
                                <th>{% trans "Number" %}</th>
                                <th>{% trans "Context" %}</th>
                                <th>{% trans "Actions" %}</th>
                            </tr>
                        </thead>
                        <tbody>

                            {% for ext in extensions %}
                                <tr>
                                    <td>
                                        <p class="list-item-heading">{{ ext.name }}</p>
                                    </td>
                                    <td>
                                        <p class="text-muted">{{ ext.number }}</p>
                                    </td>
                                    <td>
                                        <p class="text-muted">{{ ext.context }}</p>
                                    </td>
                                    <td>
                                        <a href="{% url "xbee_extensions:extension_detail" ext.pk %}" data-toggle="tooltip" data-placement="top" title="{% trans "Edit" %}">
                                            <i class="simple-icon-pencil"></i>
                                        </a>
                                    </td>
                                </tr>
                            {% endfor %}

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block js_body_block %}
    <script src="{% static "js/vendor/datatables.min.js" %}"></script>
{% endblock %}