xbee/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.apps import apps


urlpatterns = i18n_patterns(
    path('administration/', admin.site.urls),
    path('', include('xbee_account.urls')),

)

for app in settings.INSTALLED_APPS:
    if app.startswith('xbee_'):
        app_config = apps.get_app_config(app.rsplit('.')[0])
        if hasattr(app_config, 'urls') and app_config.urls:
            urlpatterns += i18n_patterns(
                path(f'{app_config.urls}/', include(f'{app_config.name}.urls')),
            )

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    import debug_toolbar
    urlpatterns = [
        path('debug/', include(debug_toolbar.urls)),
    ] + urlpatterns

xbee_account/urls.py
from django.urls import path

from xbee_account import views

app_name = 'xbee_account'

urlpatterns = [
    path('', views.DashboardView.as_view(), name='dashboard'),
    path('users-list/', views.users_list, name='users_list'),
    path('user/detail/<int:user_id>', views.user_detail, name='account'),
    path('user/disable/<int:user_id>', views.user_disable, name='user_disable'),

    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),

]

xbee_trunk/urls.py
from django.urls import path

from xbee_trunk import views

app_name = 'xbee_trunk'

urlpatterns = [
    path('', views.TrunksView.as_view(), name='trunk_list'),
    path('delete/<int:id_trunk>', views.DeleteTrunkView.as_view(), name='delete_trunk'),
]

xbee_trunk/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _


class Trunk(models.Model):
    YES_NO_CHOICES = (
        ('Y', _('Yes')),
        ('N', _('No'))
    )

    company = models.ForeignKey('xbee_company.Company', null=False, on_delete=models.CASCADE,
                                related_name="company_trunks", db_column='tru_comp_id')
    name = models.CharField(max_length=64, db_column='tru_name')
    hide_caller_id = models.CharField(default='N', max_length=2, choices=YES_NO_CHOICES)
    outbound_caller_id = models.CharField(max_length=64, db_column='tru_outbound_caller_id')
    max_channels = models.PositiveIntegerField(default=1, null=False, db_column='tru_max_channels')
    disable_trunk = models.CharField(default='N', max_length=2, choices=YES_NO_CHOICES)

    def __str__(self):
        return f"{self.name} [{self.company.name}]"

    class Meta:
        verbose_name = 'Trunk'
        verbose_name_plural = 'Trunks'
        db_table = 'xbee_trunk'


class SipTrunk(models.Model):
    trunk = models.ForeignKey(Trunk, null=False, on_delete=models.CASCADE, related_name="trunk_sip_trunks",
                              db_column="st_trunk_id")
    og_trunk_name = models.CharField(max_length=64, db_column='st_og_trunk_name')
    og_peer_details = models.TextField(db_column='st_og_peer_details')

    ic_user_context = models.CharField(max_length=64, null=True, db_column='st_ic_user_context')
    ic_user_details = models.TextField(null=True, db_column='st_ic_user_details')
    ic_register_string = models.CharField(max_length=64, null=True, db_column='st_ic_register_string')

    def __str__(self):
        return f"{self.og_trunk_name} [{self.trunk.name}]"

    class Meta:
        verbose_name = 'SipTrunk'
        verbose_name_plural = 'SipTrunks'
        db_table = 'xbee_siptrunk'

xbee_trunk/forms.py
from django import forms
from django.forms import ModelForm

from xbee_trunk.models import Trunk, SipTrunk


class TrunkForm(ModelForm):

    og_trunk_name = forms.CharField()
    og_peer_details = forms.CharField(widget=forms.Textarea)

    ic_user_context = forms.CharField(required=False)
    ic_user_details = forms.CharField(widget=forms.Textarea, required=False)
    ic_register_string = forms.CharField(required=False)

    def save_sip_trunks(self):
        """
        Call this method after the save method
        Store into db the sip trunk information
        """
        if self.cleaned_data['og_trunk_name'] \
                and self.cleaned_data['og_peer_details']:
            SipTrunk(
                trunk=self.instance,
                og_trunk_name=self.cleaned_data['og_trunk_name'],
                og_peer_details=self.cleaned_data['og_peer_details'] if self.cleaned_data['og_peer_details'] else None,
                ic_user_context=self.cleaned_data['ic_user_context'] if self.cleaned_data['ic_user_context'] else None,
                ic_user_details=self.cleaned_data['ic_user_details'] if self.cleaned_data['ic_user_details'] else None,
                ic_register_string=
                self.cleaned_data['ic_register_string'] if self.cleaned_data['ic_register_string'] else None
            ).save()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if initial := kwargs.get('initial'):
            if comps := initial.get('companies', False):
                self.fields['company'].queryset = comps

    class Meta:
        model = Trunk
        fields = '__all__'

xbee_trunk/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.utils.translation import ugettext_lazy as _

from utils.base_class_view import BaseClassView
from xbee_trunk.forms import TrunkForm
from xbee_trunk.models import Trunk


class TrunksView(LoginRequiredMixin, BaseClassView):
    """
        List all trunk and allows to create a new one
    """

    template_name = 'xbee_trunk/trunk_list.html'
    redirect_url = 'xbee_trunk:trunk_list'

    def post(self, request):
        form = TrunkForm(request.POST)
        if form.is_valid():
            form.save()
            form.save_sip_trunks()

            messages.success(request, _("Trunk created!"))
        else:
            messages.error(request, _("Somethings goes wrong!"))

        return redirect(self.redirect_url)

    def get(self, request):
        comps = self.get_companies_by_user(request)
        trunks = Trunk.objects.filter(company__in=comps)
        form_trunk = TrunkForm(initial={'companies': comps})

        return render(request, self.template_name, {'trunks': trunks, 'form_trunk': form_trunk})


class DeleteTrunkView(LoginRequiredMixin, BaseClassView):
    """
        delete trunk by id
    """

    redirect_url = 'xbee_trunk:trunk_list'

    def get(self, request, id_trunk):
        Trunk.objects.get(pk=id_trunk).delete()

        messages.success(request, _("Deleted!"))
        return redirect(self.redirect_url)

xbee_trunk/templates/xbee_trunk/trunk_list.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block title %}{% trans "Trunks" %}{% endblock %}

{% block css_head_block %}
    <link rel="stylesheet" href="{% static "css/vendor/bootstrap-float-label.min.css" %}" />
    <link rel="stylesheet" href="{% static "css/vendor/dataTables.bootstrap4.min.css" %}" />
    <link rel="stylesheet" href="{% static "css/vendor/datatables.responsive.bootstrap4.min.css" %}" />
{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-12">
            <h1>{% trans "Trunks" %}</h1>
            <div class="top-right-button-container">
                <button type="button" class="btn btn-primary btn-lg top-right-button mr-1 mb-2" data-toggle="modal" data-target="#newTrunkRightModal">{% trans "ADD" %}</button>
            </div>
            <nav class="breadcrumb-container d-none d-sm-block d-lg-inline-block" aria-label="breadcrumb">
                <ol class="breadcrumb pt-0">
                    <li class="breadcrumb-item"><a href="{% url "xbee_account:dashboard" %}">{% trans "Home" %}</a></li>
                    <li class="breadcrumb-item active" aria-current="page">{% trans "Trunks" %}</li>
                </ol>
            </nav>
            <div class="separator mb-5"></div>
        </div>
    </div>

    <div class="row mb-4">
        <div class="col-12">
            <div class="card">
                <div class="card-body">

                    <table class="data-table data-tables-pagination responsive nowrap" data-order="[[ 1, &quot;desc&quot; ]]">
                        <thead>
                            <tr>
                                <th>{% trans "Name" %}</th>
                                <th>{% trans "Company" %}</th>
                                <th>{% trans "Description" %}</th>
                                <th>{% trans "Actions" %}</th>
                            </tr>
                        </thead>
                        <tbody>

                            {% for trunk in trunks %}
                                <tr>
                                    <td>
                                        <p class="list-item-heading">{{ trunk.name }}</p>
                                    </td>
                                    <td>
                                        <p class="text-muted">{{ trunk.company.name }}</p>
                                    </td>
                                    <td>
                                        <p class="text-muted">{{ trunk.description }}</p>
                                    </td>
                                    <td>
                                        <a href="{% url 'xbee_trunk:delete_trunk' trunk.pk %}" data-toggle="tooltip" data-placement="top" title="{% trans "Delete" %}"><i class="simple-icon-trash"></i></a>
                                    </td>
                                </tr>
                            {% endfor %}

                        </tbody>
                    </table>

                </div>
            </div>
        </div>
    </div>

    <div class="modal fade modal-right" id="newTrunkRightModal" tabindex="-1" role="dialog" aria-labelledby="rightModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="rightModalLabel">{% trans "Add new trunk" %}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>{% blocktrans %} <!-- TODO --> {% endblocktrans %}{% lorem 30 w %}</p>

                    {% with submit_text="Create" submit_name="trunk_submitted" form=form_trunk %}{% include "form-top-labels-over-line.html" %}{% endwith %}
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block js_body_block %}
    <script src="{% static "js/vendor/datatables.min.js" %}"></script>
{% endblock %}