xbee/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.apps import apps


urlpatterns = i18n_patterns(
    path('administration/', admin.site.urls),
    path('', include('xbee_account.urls')),

)

for app in settings.INSTALLED_APPS:
    if app.startswith('xbee_'):
        app_config = apps.get_app_config(app.rsplit('.')[0])
        if hasattr(app_config, 'urls') and app_config.urls:
            urlpatterns += i18n_patterns(
                path(f'{app_config.urls}/', include(f'{app_config.name}.urls')),
            )

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    import debug_toolbar
    urlpatterns = [
        path('debug/', include(debug_toolbar.urls)),
    ] + urlpatterns

xbee_account/urls.py
from django.urls import path

from xbee_account import views

app_name = 'xbee_account'

urlpatterns = [
    path('', views.DashboardView.as_view(), name='dashboard'),
    path('users-list/', views.users_list, name='users_list'),
    path('user/detail/<int:user_id>', views.user_detail, name='account'),
    path('user/disable/<int:user_id>', views.user_disable, name='user_disable'),

    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),

]

xbee_time_groups/urls.py
from django.urls import path

from xbee_time_groups import views

app_name = 'xbee_time_groups'

urlpatterns = [
    path('', views.TimeGroupsView.as_view(), name='tg_list'),
    path('detail/<int:id_tg>', views.TimeGroupDetailView.as_view(), name='tg_detail'),
    path('delete/<int:id_tg>', views.DeleteTimeGroupView.as_view(), name='delete_tg'),
    path('time/delete/<int:id_t>', views.DeleteTimeView.as_view(), name='delete_time'),

]

xbee_time_groups/models.py
import pytz
from django.db import models
from django.urls import reverse
from django.utils.dates import MONTHS, WEEKDAYS


class TimeGroup(models.Model):
    company = models.ForeignKey('xbee_company.Company', null=False, on_delete=models.CASCADE,
                                related_name="company_timegroups", db_column='tg_comp_id')
    description = models.TextField(db_column='tg_description')

    def __str__(self):
        return f"{self.description} [{self.company.name}]"

    def get_absolute_url(self):
        return reverse("xbee_time_groups:tg_detail", kwargs={"id_tg": self.pk})

    class Meta:
        verbose_name = 'TimeGroup'
        verbose_name_plural = 'TimeGroups'
        db_table = 'xbee_timegroup'


class Time(models.Model):
    time_group = models.ForeignKey(TimeGroup, null=False, on_delete=models.CASCADE, related_name="times",
                                   db_column='tm_tg_id')
    time_start = models.TimeField(db_column='tm_time_start')
    time_finish = models.TimeField(db_column='tm_time_finish')
    weekday_start = models.IntegerField(choices=list(WEEKDAYS.items()), db_column='tm_weekday_start')
    weekday_finish = models.IntegerField(choices=list(WEEKDAYS.items()), db_column='tm_weekday_finish')
    month_start = models.IntegerField(choices=list(MONTHS.items()), db_column='tm_month_start')
    month_finish = models.IntegerField(choices=list(MONTHS.items()), db_column='tm_month_finish')

    TIMEZONES = ((None, '---------'), ) + tuple(zip(pytz.all_timezones, pytz.all_timezones))
    time_zone = models.CharField(max_length=60, choices=TIMEZONES, null=True, default=None, db_column='tm_time_zone')
    year_start = models.IntegerField(db_column='tm_year_start')
    year_finish = models.IntegerField(db_column='tm_year_end')

    def __str__(self):
        return f"{self.weekday_start}:{self.weekday_finish} | {self.month_start}:{self.month_finish}" \
               f" [{self.time_group.description}]"

    class Meta:
        verbose_name = 'Time'
        verbose_name_plural = 'Times'
        db_table = 'xbee_time'

xbee_time_groups/forms.py
from django.forms import ModelForm, formset_factory

from xbee_time_groups.models import TimeGroup, Time


class TimeGroupForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if initial := kwargs.get('initial'):
            if comps := initial.get('companies', False):
                self.fields['company'].queryset = comps

    class Meta:
        model = TimeGroup
        fields = '__all__'


class TimeForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['weekday_start'].new_group = 'true'
        self.fields['month_start'].new_group = 'true'
        self.fields['year_start'].new_group = 'true'
        self.fields['time_zone'].required = False

    class Meta:
        model = Time
        fields = '__all__'
        exclude = ('time_group', )


TimeFormset = formset_factory(TimeForm)

xbee_time_groups/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404

from django.utils.translation import ugettext_lazy as _

from utils.base_class_view import BaseClassView
from xbee_company.models import Company
from xbee_time_groups.forms import TimeGroupForm, TimeFormset
from xbee_time_groups.models import TimeGroup, Time


class TimeGroupsView(LoginRequiredMixin, BaseClassView):
    """
        List all time groups and allows to create a new one
    """

    template_name = 'xbee_time_groups/tg_list.html'
    redirect_url = 'xbee_time_groups:tg_list'

    def post(self, request):
        form = TimeGroupForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, _("Time group created!"))
            return redirect(form.instance)
        else:
            messages.error(request, _("Somethings goes wrong!"))

        return redirect(self.redirect_url)

    def get(self, request):
        comps = self.get_companies_by_user(request)
        form_tg = TimeGroupForm(initial={'companies': comps})
        tgs = TimeGroup.objects.filter(company__in=comps)
        return render(request, self.template_name, {'tgs': tgs, 'form_tg': form_tg})


class TimeGroupDetailView(LoginRequiredMixin, BaseClassView):
    """
        Detail of a time group, this view allows to edit the details of the time group and create it's time
    """

    template_name = 'xbee_time_groups/tg_detail.html'

    def post(self, request, id_tg):
        tg = get_object_or_404(TimeGroup, pk=id_tg)
        if 'tg_detail_submitted' in request.POST:
            form = TimeGroupForm(request.POST, instance=tg)
            if form.is_valid():
                form.save()
                messages.success(request, _("Time group updated!"))
                return redirect(form.instance)
            else:
                messages.error(request, _("Somethings goes wrong!"))

        elif 'fs_t_submitted' in request.POST:
            formset = TimeFormset(request.POST)
            if formset.is_valid():
                for form in formset:
                    if form.is_valid():
                        t = form.save(commit=False)
                        t.time_group = tg
                        t.save()
                        messages.success(
                            request,
                            _(f"Time created: "
                              f"{t.get_month_start_display()} - {t.get_month_finish_display()} | "
                              f"{t.get_weekday_start_display()} - {t.get_weekday_finish_display()} "
                              f"[{t.time_start} / {t.time_finish}]")
                        )

        return redirect(tg)

    def get(self, request, id_tg):
        tg = get_object_or_404(TimeGroup, pk=id_tg)
        comps = Company.objects.filter(pk=tg.company.pk)
        form_tg_detail = TimeGroupForm(instance=tg, initial={'companies': comps})
        t_formset = TimeFormset()

        return render(request, self.template_name, {
            'tg': tg,
            'form_tg_detail': form_tg_detail,
            't_formset': t_formset
        })


class DeleteTimeGroupView(LoginRequiredMixin, BaseClassView):
    """
        delete time group by id
    """

    redirect_url = 'xbee_time_groups:tg_list'

    def get(self, request, id_tg):
        TimeGroup.objects.get(pk=id_tg).delete()
        messages.success(request, _("Deleted!"))

        return redirect(self.redirect_url)


class DeleteTimeView(LoginRequiredMixin, BaseClassView):
    """
        delete time by id
    """

    def get(self, request, id_t):
        t = Time.objects.get(pk=id_t)
        tg = t.time_group
        t.delete()
        messages.success(request, _("Deleted!"))

        return redirect(tg)

xbee_time_groups/templates/xbee_time_groups/tg_detail.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block title %}{{ tg.description }} ~ {% trans "Time group detail" %}{% endblock %}

{% block css_head_block %}
    <link rel="stylesheet" href="{% static "css/vendor/bootstrap-float-label.min.css" %}" />
    <link rel="stylesheet" href="{% static "css/vendor/bootstrap-datepicker3.min.css" %}" />
    <link rel="stylesheet" href="{% static "css/vendor/bootstrap-datetimepicker.min.css" %}" />
{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-12">
            <h1>{% trans "Time group detail" %}</h1>
            <nav class="breadcrumb-container d-none d-sm-block d-lg-inline-block" aria-label="breadcrumb">
                <ol class="breadcrumb pt-0">
                    <li class="breadcrumb-item"><a href="{% url "xbee_account:dashboard" %}">{% trans "Home" %}</a></li>
                    <li class="breadcrumb-item"><a href="{% url "xbee_time_groups:tg_list" %}">{% trans "Time group list" %}</a></li>
                    <li class="breadcrumb-item active" aria-current="page">{{ tg.description }} ~ {% trans "Time group detail" %}</li>
                </ol>
            </nav>
            <div class="separator mb-5"></div>
        </div>
    </div>

    <div class="row mb-4">
        <div class="col-12">
            <div class="card">
                <div class="card-body">

                    {% with submit_text="Edit" submit_name="tg_detail_submitted" form=form_tg_detail %}{% include "form-grid.html" %}{% endwith %}

                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <h2>{% trans "Times" %}</h2>
        </div>
    </div>

    <div class="row mb-4">
        {% for tt in tg.times.all %}
            <div class="col-lg-3 col-md-4 col-sm-12 mb-2">
                <div class="card d-flex flex-row">
                    <div class=" d-flex flex-grow-1 min-width-zero">
                        <div class="card-body align-self-center d-flex flex-column flex-lg-row justify-content-between min-width-zero">
                            <div class="min-width-zero text-center mx-auto">
                                <p class="list-item-heading mb-1 truncate">{{ tt.get_month_start_display }} - {{ tt.get_month_finish_display }}</p>
                                <p class="list-item-heading mb-1 truncate">{{ tt.get_weekday_start_display }} - {{ tt.get_weekday_finish_display }}</p>
                                <p class="list-item-heading mb-1 truncate">{{ tt.time_start }} / {{ tt.time_finish }}</p>
                                <a href="{% url 'xbee_time_groups:delete_time' tt.pk %} "><button type="button" class="btn btn-xs btn-outline-primary mt-2">{% trans "Delete" %}</button></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                        {% with submit_text="Create" submit_name="fs_t_submitted" formset=t_formset %}{% include "formset-grid.html" %}{% endwith %}
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block js_body_block %}
    <script src="{% static "js/formset.js" %}"></script>
    <script src="{% static "js/vendor/bootstrap-datepicker.js" %}"></script>
    <script src="{% static "js/vendor/moment.min.js" %}" ></script>
    <script src="{% static "js/vendor/bootstrap-datetimepicker.min.js" %}"></script>

    <script>

        $(function() {
            initPicker();

            $('.formset').on('add-form-row', function () {
                setTimeout(function(){
                    initPicker();
                }, 200);
            });
        });

        function initPicker() {
            $('.datetimepicker').datetimepicker({
                format: 'HH:mm',
                icons: {
                    up: 'simple-icon-arrow-up',
                    down: 'simple-icon-arrow-down'
                },
            });

            $('[id$=year_start]').datepicker({
                format: "yyyy",
                viewMode: "years",
                minViewMode: "years",
            });

            $('[id$=year_finish]').datepicker({
                format: "yyyy",
                viewMode: "years",
                minViewMode: "years",
            });
        }
    </script>
{% endblock %}

xbee_time_groups/templates/xbee_time_groups/tg_list.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block title %}{% trans "Time Groups" %}{% endblock %}

{% block css_head_block %}
    <link rel="stylesheet" href="{% static "css/vendor/bootstrap-float-label.min.css" %}" />
    <link rel="stylesheet" href="{% static "css/vendor/dataTables.bootstrap4.min.css" %}" />
    <link rel="stylesheet" href="{% static "css/vendor/datatables.responsive.bootstrap4.min.css" %}" />
{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-12">
            <h1>{% trans "Time Groups" %}</h1>
            <div class="top-right-button-container">
                <button type="button" class="btn btn-primary btn-lg top-right-button mr-1 mb-2" data-toggle="modal" data-target="#newTGRightModal">{% trans "ADD" %}</button>
            </div>
            <nav class="breadcrumb-container d-none d-sm-block d-lg-inline-block" aria-label="breadcrumb">
                <ol class="breadcrumb pt-0">
                    <li class="breadcrumb-item"><a href="{% url "xbee_account:dashboard" %}">{% trans "Home" %}</a></li>
                    <li class="breadcrumb-item active" aria-current="page">{% trans "Time Groups" %}</li>
                </ol>
            </nav>
            <div class="separator mb-5"></div>
        </div>
    </div>

    <div class="row mb-4">
        <div class="col-12">
            <div class="card">
                <div class="card-body">

                    <table class="data-table data-tables-pagination responsive nowrap" data-order="[[ 1, &quot;desc&quot; ]]">
                        <thead>
                            <tr>
                                <th>{% trans "Company" %}</th>
                                <th>{% trans "Description" %}</th>
                                <th>{% trans "Actions" %}</th>
                            </tr>
                        </thead>
                        <tbody>

                            {% for tg in tgs %}
                                <tr>
                                    <td>
                                        <p class="list-item-heading">{{ tg.company.name }}</p>
                                    </td>
                                    <td>
                                        <p class="text-muted">{{ tg.description }}</p>
                                    </td>
                                    <td>
                                        <a href="{{ tg.get_absolute_url }}" data-toggle="tooltip" data-placement="top" title="{% trans "Edit" %}" class="mr-3"><i class="simple-icon-pencil"></i></a>
                                        <a href="{% url 'xbee_time_groups:delete_tg' tg.pk %}" data-toggle="tooltip" data-placement="top" title="{% trans "Delete" %}"><i class="simple-icon-trash"></i></a>
                                    </td>
                                </tr>
                            {% endfor %}

                        </tbody>
                    </table>

                </div>
            </div>
        </div>
    </div>

    <div class="modal fade modal-right" id="newTGRightModal" tabindex="-1" role="dialog" aria-labelledby="rightModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="rightModalLabel">{% trans "Add new time group" %}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>{% blocktrans %} <!-- TODO --> {% endblocktrans %}{% lorem 30 w %}</p>

                    {% with submit_text="Create" submit_name="tg_submitted" form=form_tg %}{% include "form-top-labels-over-line.html" %}{% endwith %}
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block js_body_block %}
    <script src="{% static "js/vendor/datatables.min.js" %}"></script>
{% endblock %}