xbee/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.apps import apps


urlpatterns = i18n_patterns(
    path('administration/', admin.site.urls),
    path('', include('xbee_account.urls')),

)

for app in settings.INSTALLED_APPS:
    if app.startswith('xbee_'):
        app_config = apps.get_app_config(app.rsplit('.')[0])
        if hasattr(app_config, 'urls') and app_config.urls:
            urlpatterns += i18n_patterns(
                path(f'{app_config.urls}/', include(f'{app_config.name}.urls')),
            )

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    import debug_toolbar
    urlpatterns = [
        path('debug/', include(debug_toolbar.urls)),
    ] + urlpatterns

xbee_account/urls.py
from django.urls import path

from xbee_account import views

app_name = 'xbee_account'

urlpatterns = [
    path('', views.DashboardView.as_view(), name='dashboard'),
    path('users-list/', views.users_list, name='users_list'),
    path('user/detail/<int:user_id>', views.user_detail, name='account'),
    path('user/disable/<int:user_id>', views.user_disable, name='user_disable'),

    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),

]

xbee_recordings/urls.py
from django.urls import path

from xbee_recordings import views

app_name = 'xbee_recordings'

urlpatterns = [
    path('system-recording', views.SystemRecordingsView.as_view(), name='system_recording'),
    path('music-on-holding', views.MusicOnHoldingsView.as_view(), name='music_on_holding'),
    path('download/<int:id_recording>', views.DownloadRecordingView.as_view(), name='download_recording'),
    path('delete/<int:id_recording>', views.DeleteRecordingView.as_view(), name='delete_recording'),

]

xbee_recordings/models.py
from django.contrib.contenttypes.models import ContentType
from django.db import models

from django.utils.translation import ugettext_lazy as _
from django.utils.translation import ugettext as _t


class RecordingFile(models.Model):
    converted_file = models.BinaryField(db_column='recfl_converted_file')
    recording = models.ForeignKey('Recording', null=False, on_delete=models.CASCADE, related_name="recording_file",
                                  db_column='recfl_rec_id')

    def __str__(self):
        return self.recording.company.name

    class Meta:
        verbose_name = 'RecordingFile'
        verbose_name_plural = 'RecordingFiles'
        db_table = 'xbee_recordingfile'


class Recording(models.Model):
    company = models.ForeignKey('xbee_company.Company', null=False, on_delete=models.CASCADE,
                                related_name="company_recordings", db_column='rec_comp_id')
    real_type = models.ForeignKey(ContentType, on_delete=models.CASCADE, editable=False)

    FORMAT_CHOICES = (
        ('wav', _('WAV')),
    )
    convert_to = models.CharField(default='wav', choices=FORMAT_CHOICES, max_length=5, db_column='rec_convert_to')

    def __str__(self):
        return self.company.name

    def get_real_type(self):
        return ContentType.objects.get_for_model(type(self))

    def save(self, *args, **kwargs):
        if self._state.adding:
            self.real_type = self.get_real_type()
        super(Recording, self).save(*args, **kwargs)

    def cast(self):
        return self.real_type.get_object_for_this_type(pk=self.pk)

    class Meta:
        verbose_name = 'Recording'
        verbose_name_plural = 'Recordings'
        db_table = 'xbee_recording'


class SystemRecording(Recording):
    name = models.CharField(max_length=30, null=False, blank=False, db_column='srec_name')
    description = models.TextField(db_column='srec_description')

    def __str__(self):
        return f"{self.company.name} - {self.name}"

    class Meta:
        verbose_name = 'SystemRecording'
        verbose_name_plural = 'SystemRecordings'
        db_table = 'xbee_systemrecording'


class MusicOnHolding(Recording):
    is_random_play = models.BooleanField(default=False, db_column='moh_is_random_play')
    category = models.ForeignKey('MusicOnHoldingCategory', null=False, on_delete=models.CASCADE,
                                 related_name="music_category", db_column='moh_mohcategory_id')

    def __str__(self):
        return self.company.name

    class Meta:
        verbose_name = 'MusicOnHolding'
        verbose_name_plural = 'MusicOnHoldings'
        db_table = 'xbee_musiconholding'


class MusicOnHoldingCategory(models.Model):
    name = models.CharField(max_length=30, null=False, blank=False, db_column='mohc_name')
    company = models.ForeignKey('xbee_company.Company', null=False, on_delete=models.CASCADE,
                                related_name="company_music_categories", db_column='mohc_comp_id')

    def __str__(self):
        return _t(f'{self.name} - [Company: {self.company.name}]')

    class Meta:
        verbose_name = 'MusicOnHoldingCategory'
        verbose_name_plural = 'MusicOnHoldingCategories'
        db_table = 'xbee_musiconholdingcategory'

xbee_recordings/forms.py
from django.forms import ModelForm
from django import forms

from xbee_recordings.models import MusicOnHolding, SystemRecording, MusicOnHoldingCategory


class MusicOnHoldingForm(ModelForm):
    source_file = forms.FileField()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if initial := kwargs.get('initial'):
            if categs := initial.get('categories', False):
                self.fields['category'].queryset = categs

            if comps := initial.get('companies', False):
                self.fields['company'].queryset = comps

    class Meta:
        model = MusicOnHolding
        fields = '__all__'


class SystemRecordingForm(ModelForm):
    source_file = forms.FileField()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if initial := kwargs.get('initial'):
            if comps := initial.get('companies', False):
                self.fields["company"].queryset = comps

    class Meta:
        model = SystemRecording
        fields = '__all__'


class MusicOnHoldingCategoryForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if initial := kwargs.get('initial'):
            if comps := initial.get('companies', False):
                self.fields["company"].queryset = comps

    class Meta:
        model = MusicOnHoldingCategory
        fields = '__all__'

xbee_recordings/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction
from django.db.models import ProtectedError
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.utils.translation import ugettext_lazy as _

from utils.base_class_view import BaseClassView
from xbee_recordings.forms import MusicOnHoldingForm, MusicOnHoldingCategoryForm, SystemRecordingForm
from xbee_recordings.models import MusicOnHolding, MusicOnHoldingCategory, SystemRecording, RecordingFile, Recording
from xbee_recordings.audio_utils import save_recording_file, format_conversion, clean_temp_files, \
    get_source_path_file, from_memory_to_base64


class SystemRecordingsView(LoginRequiredMixin, BaseClassView):
    """
        List and create the system recordings
    """

    template_name = 'xbee_recordings/system_recordings.html'
    redirect_url = 'xbee_recordings:system_recording'

    def post(self, request):
        if 'sysr_submitted' in request.POST:
            form = SystemRecordingForm(request.POST, request.FILES)
            if form.is_valid():
                try:
                    # atomic transaction, if something in the conversion was wrong the MusicOnHolding was deleted
                    with transaction.atomic():
                        src_file_path = get_source_path_file(request)

                        new_sysr = form.save(commit=False)
                        new_sysr.save()

                        # format conversion, store into db
                        converted_file = format_conversion(new_sysr, src_file_path)
                        save_recording_file(new_sysr, converted_file.name)

                        messages.success(request, _("System recording created!"))
                except Exception:
                    messages.error(request, _("Somethings goes wrong!"))
                finally:
                    # cleaning
                    clean_temp_files(src_file_path, converted_file)

            else:
                messages.error(request, _("Somethings goes wrong!"))

        return redirect(self.redirect_url)

    def get(self, request):
        comps = self.get_companies_by_user(request)
        sysrec = SystemRecording.objects.filter(company__in=comps)
        form_sysr = SystemRecordingForm(initial={'companies': comps})

        return render(request, self.template_name, {
            'form_sysr': form_sysr,
            'sysrec': sysrec
        })


class MusicOnHoldingsView(LoginRequiredMixin, BaseClassView):
    """
        List and create the music on holding and categories
    """

    template_name = 'xbee_recordings/music_on_holding.html'
    redirect_url = 'xbee_recordings:music_on_holding'

    def post(self, request):
        if 'moh_submitted' in request.POST:
            form = MusicOnHoldingForm(request.POST, request.FILES)
            if form.is_valid():
                try:
                    # atomic transaction, if something in the conversion was wrong the MusicOnHolding was deleted
                    with transaction.atomic():
                        src_file_path = get_source_path_file(request)

                        new_moh = form.save(commit=False)
                        new_moh.save()

                        # format conversion, store into db
                        converted_file = format_conversion(new_moh, src_file_path)
                        save_recording_file(new_moh, converted_file.name)

                        messages.success(request, _("Music on holding created!"))
                except Exception:
                    messages.error(request, _("Somethings goes wrong!"))
                finally:
                    # cleaning
                    clean_temp_files(src_file_path, converted_file)
            else:
                messages.error(request, _("Somethings goes wrong!"))

        if 'moh_category_submitted' in request.POST:
            form = MusicOnHoldingCategoryForm(request.POST)
            if form.is_valid():
                form.save()
                messages.success(request, _("Category created!"))
            else:
                messages.error(request, _("Somethings goes wrong!"))

        return redirect(self.redirect_url)

    def get(self, request):
        comps = self.get_companies_by_user(request)
        categories = MusicOnHoldingCategory.objects.filter(company__in=comps)
        music = MusicOnHolding.objects.filter(category__in=categories)
        form_moh = MusicOnHoldingForm(initial={'categories': categories, 'companies': comps})
        form_moh_category = MusicOnHoldingCategoryForm(initial={'companies': comps})

        return render(request, self.template_name, {
            'form_moh': form_moh,
            'form_moh_category': form_moh_category,
            'music': music, 'categories': categories
        })


class DownloadRecordingView(LoginRequiredMixin, BaseClassView):
    """
        Selects the file stored into the db and return base64 encode of them
    """

    def get(self, request, id_recording):
        base64_file = from_memory_to_base64(
            RecordingFile.objects.get(recording__pk=id_recording).converted_file
        )
        return HttpResponse(base64_file, content_type='text/plain', status=200)


class DeleteRecordingView(LoginRequiredMixin, BaseClassView):
    """
        delete recordings by id
    """

    def get(self, request, id_recording):
        recs = Recording.objects.get(pk=id_recording)
        if recs.real_type.model == 'musiconholding':
            redirect_to = 'music_on_holding'
        elif recs.real_type.model == 'systemrecording':
            redirect_to = 'system_recording'

        try:
            recs.delete()
            messages.success(request, _("Deleted!"))
        except ProtectedError as e:
            context = {'queryset': e.protected_objects}
            html_content = render_to_string('exception-message-template.html', context)
            messages.warning(
                request,
                _("This file is associated with another module, please remove the association and try again.")
                + html_content
            )

        return redirect(f'xbee_recordings:{redirect_to}')

xbee_recordings/templates/xbee_recordings/music_on_holding.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block title %}{% trans "Music on holding" %}{% endblock %}

{% block css_head_block %}
    <link rel="stylesheet" href="{% static "css/vendor/bootstrap-float-label.min.css" %}" />
    <link rel="stylesheet" href="{% static "css/vendor/dataTables.bootstrap4.min.css" %}" />
    <link rel="stylesheet" href="{% static "css/vendor/datatables.responsive.bootstrap4.min.css" %}" />
{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-12">
            <h1>{% trans "Music on holding" %}</h1>
            <div class="top-right-button-container">
                <button type="button" class="btn btn-primary btn-lg top-right-button mr-1 mb-2" data-toggle="modal" data-target="#newMohRightModal">{% trans "ADD MUSIC" %}</button>
                <button type="button" class="btn btn-primary btn-lg top-right-button mr-1 mb-2" data-toggle="modal" data-target="#newMohCategoryRightModal">{% trans "ADD CATEGORY" %}</button>
            </div>
            <nav class="breadcrumb-container d-none d-sm-block d-lg-inline-block" aria-label="breadcrumb">
                <ol class="breadcrumb pt-0">
                    <li class="breadcrumb-item"><a href="{% url "xbee_account:dashboard" %}">{% trans "Home" %}</a></li>
                    <li class="breadcrumb-item active" aria-current="page">{% trans "Music on holding" %}</li>
                </ol>
            </nav>
            <div class="separator mb-5"></div>
        </div>
    </div>

    <div class="row mb-4">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <ul class="nav nav-tabs card-header-tabs " role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" id="first-tab" data-toggle="tab" href="#music__holdings" role="tab" aria-controls="first" aria-selected="true">{% trans "Music" %}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="second-tab" data-toggle="tab" href="#music__categories" role="tab" aria-controls="second" aria-selected="false">{% trans "Categories" %}</a>
                        </li>
                    </ul>
                </div>

                <div class="card-body">

                    <div class="tab-content">
                        <div class="tab-pane fade show active" id="music__holdings" role="tabpanel" aria-labelledby="first-tab">

                            {% include "xbee_recordings/tab/music.html" %}

                        </div>
                        <div class="tab-pane fade" id="music__categories" role="tabpanel" aria-labelledby="second-tab">

                            {% include "xbee_recordings/tab/category.html" %}

                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>

    <div class="modal fade modal-right" id="newMohRightModal" tabindex="-1" role="dialog" aria-labelledby="rightModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="rightModalLabel">{% trans "Add new music" %}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>{% blocktrans %} <!-- TODO --> {% endblocktrans %}{% lorem 30 w %}</p>

                    {% with submit_text="Create" submit_name="moh_submitted" form=form_moh %}{% include "form-top-labels-over-line.html" %}{% endwith %}
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade modal-right" id="newMohCategoryRightModal" tabindex="-1" role="dialog" aria-labelledby="rightModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="rightModalLabel">{% trans "Add new category" %}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>{% blocktrans %} <!-- TODO --> {% endblocktrans %}{% lorem 30 w %}</p>

                    {% with submit_text="Create" submit_name="moh_category_submitted" form=form_moh_category %}{% include "form-top-labels-over-line.html" %}{% endwith %}
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block js_body_block %}
    <script src="{% static "js/vendor/datatables.min.js" %}"></script>
    <script src="{% static "xbee_recordings/recordings.js" %}"></script>
{% endblock %}

xbee_recordings/templates/xbee_recordings/system_recordings.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block title %}{% trans "System Recording" %}{% endblock %}

{% block css_head_block %}
    <link rel="stylesheet" href="{% static "css/vendor/bootstrap-float-label.min.css" %}" />
    <link rel="stylesheet" href="{% static "css/vendor/dataTables.bootstrap4.min.css" %}" />
    <link rel="stylesheet" href="{% static "css/vendor/datatables.responsive.bootstrap4.min.css" %}" />
{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-12">
            <h1>{% trans "System Recording" %}</h1>
            <div class="top-right-button-container">
                <button type="button" class="btn btn-primary btn-lg top-right-button mr-1" data-toggle="modal" data-target="#newSystemRecordingRightModal">{% trans "ADD" %}</button>
            </div>
            <nav class="breadcrumb-container d-none d-sm-block d-lg-inline-block" aria-label="breadcrumb">
                <ol class="breadcrumb pt-0">
                    <li class="breadcrumb-item"><a href="{% url "xbee_account:dashboard" %}">{% trans "Home" %}</a></li>
                    <li class="breadcrumb-item active" aria-current="page">{% trans "System Recording" %}</li>
                </ol>
            </nav>
            <div class="separator mb-5"></div>
        </div>
    </div>

    <div class="row mb-4">
        <div class="col-12">
            <div class="card">
                <div class="card-body">

                    <table class="data-table data-tables-pagination responsive nowrap" data-order="[[ 1, &quot;desc&quot; ]]">
                        <thead>
                            <tr>
                                <th>{% trans "Name" %}</th>
                                <th>{% trans "Description" %}</th>
                                <th>{% trans "Company" %}</th>
                                <th>{% trans "File" %}</th>
                                <th>{% trans "Actions" %}</th>
                            </tr>
                        </thead>
                        <tbody>

                            {% for sr in sysrec %}
                                <tr>
                                    <td>
                                        <p class="list-item-heading">{{ sr.name }}</p>
                                    </td>
                                    <td>
                                        <p class="text-muted">{{ sr.description }}</p>
                                    </td>
                                    <td>
                                        <p class="text-muted">{{ sr.company.name }}</p>
                                    </td>
                                    <td>
                                        <p class="text-muted"><button type="button" id="music-{{ sr.pk }}" onclick="downlaodRecording(this);" url="{% url 'xbee_recordings:download_recording' sr.pk %}" class="btn btn-secondary btn-sm">{% trans "LISTEN" %}</button></p>
                                    </td>
                                    <td><a href="{% url 'xbee_recordings:delete_recording' sr.pk %}" data-toggle="tooltip" data-placement="top" title="{% trans "Delete" %}"><i class="simple-icon-trash"></i></a></td>
                                </tr>
                            {% endfor %}

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade modal-right" id="newSystemRecordingRightModal" tabindex="-1" role="dialog" aria-labelledby="rightModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="rightModalLabel">{% trans "Add new system recording" %}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>{% blocktrans %} <!-- TODO --> {% endblocktrans %}{% lorem 30 w %}</p>

                    {% with submit_text="Create" submit_name="sysr_submitted" form=form_sysr %}{% include "form-top-labels-over-line.html" %}{% endwith %}
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block js_body_block %}
    <script src="{% static "js/vendor/datatables.min.js" %}"></script>
    <script src="{% static "xbee_recordings/recordings.js" %}"></script>
{% endblock %}